### ISSUE TITLE
Pictures in Howto

### ISSUE THREAD

**Issue by scifire91** [OCSInventory-NG/Wiki#1]
Hey,

i would like to participate a little bit in the how to section and change some outdated things. 
But first, you have many pic´s in the howtos which only show text. Do you still want to have these pictures? 
I think it´s very time consuming to take care for the pic´s. Also it is dissapointing if you expect a pic but link is broken but this is often the case.

So is it ok if i remove outdated and broken pic links?

**Comment by gillesdubois** [comment]
Hi,

Ofc you can participate to the docuementation's update.
You can make your change and submit a Pull Request.
Then i will review it and merge asap :)

It would be nice to replace only text screens by markdown code balise : ` Code syntax `

Note : Don't hesitate to ask if you have some question ( On irc / github / mail ) i will try to anwser quickly. 

Thanks for your contribution.

Regards,
Gilles Dubois.
