### ISSUE TITLE
VULN_CVESEARCH_HOST does not work with a port-number

### ISSUE THREAD

**Issue by hertell** [OCSInventory-NG/Wiki#117]
I have CVE-Search in docker, and had to change the default 443-port to something else because it conflicted with an existing service on same server.  Running php ./cron_cve.php, i got the following error:

$php ./cron_cve.php
https://localhost:5000 is not reachable.

I got this fixed after i set up in apache a reverse proxy that was listening on the default https-port, but different hostname (https://cve.mydomain.tld)

**Comment by gillesdubois** [comment]
Hi,

We added a SSL parameter / management in the latest version of OCS.

Regards,
Gilles.
