### ISSUE TITLE
Missing dependency for snmp scan

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/Wiki#118]
I'm trying to have an agent doing snmp scans

I see the following requirement:

```
sub snmp_ip_scan {
    my ($self,$net_to_scan) = @_;
    my $logger=$self->{logger};
    my $common=$self->{common};

    if ($common->can_load('Net::Netmask') ) {
        my $block=Net::Netmask->new($net_to_scan);
        my $size=$block->size()-2;
```

This dependency is not documented in the wiki.

I would gladly update the doc but I'm not sure where to do it: 
* here: https://wiki.ocsinventory-ng.org/06.Network-Discovery-with-OCS-Inventory-NG/Managing-and-using-SNMP-feature/
* or here: https://wiki.ocsinventory-ng.org/06.Network-Discovery-with-OCS-Inventory-NG/Using-SNMP-scan-feature/#configuring-unix-unified-agent

**Comment by StCyr** [comment]
on debian: apt install libnet-netmask-perl

**Comment by charleneauger** [comment]
Hi @StCyr ,

The Net::Netmask dependency is documented as a `Recommended modules` on the Setting up Unix Agent documentation : [here](http://wiki.ocsinventory-ng.org/03.Basic-documentation/Setting-up-the-UNIX-agent-manually-on-client-computers/)

Best regards,
Charlene
