### ISSUE TITLE
 ipdiscover-util.pl -scantype option doesn't exist

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/Wiki#125]
Though being documented in https://wiki.ocsinventory-ng.org/06.Network-Discovery-with-OCS-Inventory-NG/Using-IP-discovery-feature/

**Comment by gillesdubois** [comment]
Hi Cyril,

Even with the 2.9 installed ?

Regards,
Gilles

**Comment by StCyr** [comment]
Hoho!

That's a good news

Where can I download it?

**Comment by fbomj** [comment]
option is not present in ipdiscover-util.pl

**Comment by StCyr** [comment]
I confirm it's present in version 2.9
