### ISSUE TITLE
SCP module installation (Using extension engine)

### ISSUE THREAD

**Issue by provelo-ict** [OCSInventory-NG/Wiki#126]
Hello,

In https://github.com/OCSInventory-NG/Wiki/blob/master/english/10.Plugin-engine/Using-plugins-installer.md, it is advised to install python3's scp module through pip using sudo.
Using pip with sudo powers is not recommended. I would rather advise to install the module using the distrubition's package.

--> instead of

```
 sudo apt install python3-pip
sudo pip3 install scp
```

--> use
`sudo apt install python3-scp`

**Comment by gillesdubois** [comment]
Hi,

This issue has been resolved.
Thanks for your contribution.

Gilles.
