### ISSUE TITLE
Error "Got timeout reading communication packets"

### ISSUE THREAD

**Issue by ocsinventory** [OCSInventory-NG/Wiki#131]
Hello OCS community,

I had been re-directed from:
https://ask.ocsinventory-ng.org/13446/error-got-timeout-reading-communication-packets
... to this place. I hope I am right here, otherwise please advice.

We are using OCS Inventory NG  in our company.

Multiple times a day I can experience the following error message in the MySQL Server 5.7 error logs with this pattern:

2021-06-27T23:56:22.342179Z 910027 [Note] Aborted connection 910027 to db: '<ocs_db>' user: '<MySQL_user_forr_ocs>' host: '<our_ocs_server>' (Got timeout reading communication packets)

This only happens in reference with the MySQL database used for OCS. There is no issue with other MySQL databases within the same server.

As to Oracle the reason for this kind of error might likely be related to that OCS is not closing down the database connections properly. The sessions remain open and after the specified timeouts passed ("interactive_timeout" and "wait_timeout) the session are closed by MySQL. This triggers the output in the error logfile.

https://support.oracle.com/epmos/faces/DocumentDisplay?_afrLoop=457345552799625&parent=EXTERNAL_SEARCH&sourceId=PROBLEM&id=2322952.1&_afrWindowMode=0&_adf.ctrl-state=7t8dq5shl_4
(login needed)

Could this be related to OCS directly ? Application issue ?
Any recommendations ?
Is anyone experiencing this as well ?

I do not know have much knowledge in OCS, please let me know, if additonal information is missing.

Many Thanks

**Comment by gillesdubois** [comment]
Hi @ocsinventory, 

Do you know which version of OCS Inventory is installed ?

Regards,
Gilles.

**Comment by ocsinventory** [comment]
Hi @gillesdubois,

this is version 2.5+dfsg1-1.

Regards
ocsinventory

**Comment by gillesdubois** [comment]
2.5 is starting to get a bit old, a lot of improvement on the databases transactions has been made with the latest version.
Upgrading to the latest would be a good first step to fix your issue I think.

Regards,
Gilles.

**Comment by ocsinventory** [comment]
Hi @gillesdubois,

many thanks. 
Might there be a chance that the Linux packages for 2.9 will be added to the official Linux Debian Repository ?
There is currently only 2.5 available.

Regards
ocsinventory

**Comment by charleneauger** [comment]
Hi @ocsinventory ,

This issue is a bit old but since we added the latest OCS server/agent versions on the debian repos.
The repo source has been changed, see the documentation : http://wiki.ocsinventory-ng.org/03.Basic-documentation/Setting-up-a-OCS-Inventory-Server-with-rpm/

Best regards,
Charlene
