### ISSUE TITLE
Modify path comunicate with agents

### ISSUE THREAD

**Issue by brunohmg89** [OCSInventory-NG/Wiki#145]
Hi,

Is it possible to change the agents update path?

I would like to change the highlighted path to another one.

![image](https://user-images.githubusercontent.com/52254114/166247292-9e649f15-9c06-4a61-8561-1da599479806.png)

**Comment by gillesdubois** [comment]
Hi,

Of course, you have to edit the location /ocsinventory to location /something in the z-ocsinventory-server.conf on the server.

Regards,
Gilles.
