### ISSUE TITLE
Repo installation

### ISSUE THREAD

**Issue by daniejstriata** [OCSInventory-NG/Wiki#15]
Will it be possible to guide installation on Centos using your Repo? I found the page explaining how to install the Repo but no steps to install. From what I guessed to install the ocs server is not configured after installing **ocsinventory-server.noarch** . The original install works for me when I run the setup script but I hope it will be more consistent installing from the repo.

**Comment by gillesdubois** [comment]
Hi @daniejstriata ,

It's a really good idea but we are not planning to do that atm.
If you are willing to help, we are searching contributors for our documentation.

Regards,
Gilles Dubois.

**Comment by daniejstriata** [comment]
I could document it but unfortunately I was not able to figure out how to config OCS after installing from the repo myself.
