### ISSUE TITLE
User and Password Encoded

### ISSUE THREAD

**Issue by AlroneRhyn** [OCSInventory-NG/Wiki#179]
Hello,

We discovered an undocumented changed introduced in ocsinventory-agent v2.6.1 regarding htpasswd auth: user and password strings passed in args or configfile must be base64 encoded.

Commit: https://github.com/OCSInventory-NG/UnixAgent/commit/2ee973db450d9b81f9c0fda519ba896487cb174e

To be changed in:
- https://github.com/OCSInventory-NG/Wiki/blob/d0438f2417860199c9b25e271d098023e3cc127d/english/03.Basic-documentation/Setting-up-the-UNIX-agent-manually-on-client-computers.md?plain=1#L282
- https://github.com/OCSInventory-NG/Wiki/blob/d0438f2417860199c9b25e271d098023e3cc127d/english/03.Basic-documentation/Setting-up-the-UNIX-agent-manually-on-client-computers.md?plain=1#L283
- https://github.com/OCSInventory-NG/Wiki/blob/d0438f2417860199c9b25e271d098023e3cc127d/english/03.Basic-documentation/Setting-up-the-UNIX-agent-manually-on-client-computers.md?plain=1#L324
- https://github.com/OCSInventory-NG/Wiki/blob/d0438f2417860199c9b25e271d098023e3cc127d/english/03.Basic-documentation/Setting-up-the-UNIX-agent-manually-on-client-computers.md?plain=1#L325

Opening an issue in ocsinventory-agent unix to update man pages and help.

Regards

**Comment by fbomj** [comment]
Fixed with #196
