### ISSUE TITLE
MariaDB Support

### ISSUE THREAD

**Issue by robertsilen** [OCSInventory-NG/Wiki#194]
Hello, I noticed the documentation page [03.Basic-documentation/Deploying-database-server/](https://wiki.ocsinventory-ng.org/03.Basic-documentation/Deploying-database-server/) states "Database server currently can only be MySQL 8.0 or higher" though the actual examples and content are referring to MariaDB - rightfully so since most distros are running MariaDB by default.

So why does the intro text mention MySQL now? Should i be changed from MySQL 8.0 to a suitable MariaDB version? Or why does it say is the current state of MariaDB compatibility? Is CI testing being done towards MariaDB?

**Comment by gillesdubois** [comment]
Hi @robertsilen 

I agree with you, the deploying database server can be confused as it make people feel like MariaDB is not supported.
I'll create a PR asap :)

Regards,
Gilles DUBOIS.

**Comment by robertsilen** [comment]
@gillesdubois Cool, thanks.

**Comment by gillesdubois** [comment]
PR Opened, I redirect to the prerequisites page instead of duplicating the information :)
