### ISSUE TITLE
Link zu missing website

### ISSUE THREAD

**Issue by Tanarri** [OCSInventory-NG/Wiki#29]
Hi,

in the wiki on page https://github.com/OCSInventory-NG/Wiki/blob/master/english/06.OCS-Tools/OCS-Packager.md is a link "setup Windows Agent 2.X" in topic "Deploying agent on a domain".

The link "setup Windows Agent 2.X" lead to a non existing website

Greetings
TanarRi

**Comment by gillesdubois** [comment]
Hi,

A pull request is available.
Once merged, the wiki will be updated automaticaly after ~1 hours. 

Thx for your contribution.

Regards,
Gilles Dubois.
