### ISSUE TITLE
Wiki for update?

### ISSUE THREAD

**Issue by scifire91** [OCSInventory-NG/Wiki#4]
Hey,
i didnt´found any entry on your wiki or on github for an update of the ocs-server. 
Do you have an how to? 
If not is there anything to pay attention  if i update from 2.3 to upcoming 2.3.1? 
maybe you could describe it in short here then i try to update the wiki here on github.

**Comment by gillesdubois** [comment]
Hi @scifire91 ,

Atm there is no doc on how to update but the process is basically the same than the other version : 

Backup your apache configurations file : 
z-ocsinventory-serve.conf
ocsinventory-resports.conf

Backup your ocs configuration : 
dbconfig.inc.php ( located in /usr/share/ocsinventory-reports/ocsreports/dbconfig.inc.php )

Download the last release.
Execute the setup.sh.

Restore configuration file.

Restart apache.

Go on the webconsole
Update the database ( if needed )

Check if everything is ok.

**Comment by scifire91** [comment]
okay, i think i will create a how to for that.
