### ISSUE TITLE
Extension engine dependencies

### ISSUE THREAD

**Issue by steffmeister** [OCSInventory-NG/Wiki#86]
On https://github.com/OCSInventory-NG/Wiki/blob/master/english/10.Plugin-engine/Using-plugins-installer.md you write about needed packages for the engine.

Aren't they only needed for the "Scripted communication server installation" part?

So the needed packages should be moved there. Also, not everyone is using a Debian-based Linux, maybe this can be extended. I am however unable to find a suiting package in my CentOS 7.

**Comment by gillesdubois** [comment]
Hi @steffmeister,

No these dependencies are necessary for additional tools that make plugin installation easier but not required by the communication server.

We will update the documentation with CentOS soon.

Regards,
Gilles Dubois.
