### ISSUE TITLE
Improve section about plugin installing

### ISSUE THREAD

**Issue by steffmeister** [OCSInventory-NG/Wiki#87]
On https://github.com/OCSInventory-NG/Wiki/blob/master/english/10.Plugin-engine/Using-plugins-installer.md it reads: "Then, place the downloaded zip file on the extensions folder of your Administration server and unzip it." Thats only half the truth, it should be mentioned that there needs to be a folder with the plugin's name! Since the downloaded extensions from github usually do not contain this folder it is a easy mistake...

**Comment by gillesdubois** [comment]
Hi @steffmeister 

Our documentation is not written with github in mind (which is more for advanced users / devs) but with our plugin platform : http://plugins.ocsinventory-ng.org

This platform directly give you the good zip file with the right name inside it.

Regards,
Gilles Dubois.
